version: '3'

services:
  apiservice:
    build:
      context: .
      dockerfile: Dockerfile_node
    container_name: apicontainer
    ports:
      - 3001:3000
    volumes:
      - .:/var/www
    networks:
      - mynetwork
    


  curlservice:
    build:
      context: .
      dockerfile: Dockerfile_curl
    container_name: curlcontainer
    networks:
      - mynetwork



networks:
  mynetwork:
    driver: bridge

